rules:

#Possible errors - https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors

  # Color
  color-no-invalid-hex: true

  #Font Family
  font-family-no-duplicate-names: true

  #Function
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true

  #String
  string-no-newline: true

  #Unit
  unit-no-unknown: true

  #Shorthand property
  shorthand-property-no-redundant-values: true

  #Property
  property-no-unknown: true

  #Keyframe declaration
  keyframe-declaration-no-important: true

  #Declaration Block
  declaration-block-no-duplicate-properties:
  - true
  - ignore:
    - consecutive-duplicates-with-different-values
  declaration-block-no-shorthand-property-overrides: true

  #Selector
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true

  #TODO: Complete Media Feature
  media-feature-name-no-unknown: true

  #General / Sheet
  #no-descending-specificity: true #Need to look into
  no-duplicate-selectors: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-unknown-animations: true




#Limit language features - https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#limit-language-features

  # Color
  color-named: never

  #Function
  function-url-no-scheme-relative: true

  #Time
  "time-min-milliseconds": 100 #According to the notes to the original issue (https://github.com/stylelint/stylelint/issues/597#issuecomment-180872504) the human eye can't see transition times under 100ms. #TODO: More resources maybe recommended to confirm.

  #Value
  value-no-vendor-prefix: true

  #Property
  property-no-vendor-prefix: true

  #Declaration
  #declaration-no-important: true #Only use when checking if !important is being used - note that !important is acceptable in utilities

  #Declaration Block
  declaration-block-single-line-max-declarations: 1 #TODO: Make this change in the future - this would allow for reduced chance of merge conflicts and would be more 'truthful' when viewing a diff - see cssguidlin.es

  #TODO: Selector
  selector-max-compound-selectors: 3
  #selector-max-specificity: 0,2,1 # Set to what works for you - https://stylelint.io/user-guide/rules/selector-max-specificity/
  selector-max-id: 0
  selector-max-universal: 0
  selector-no-vendor-prefix: true
  selector-max-empty-lines: 0

  #At-rule
  at-rule-no-vendor-prefix: true

  #Comments
  comment-no-empty: true


#Stylistic issues - https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#stylistic-issues

  # Color
  color-hex-case: lower
  color-hex-length: short

  #Font Family
  font-family-name-quotes: always-where-recommended

  #Font weight
  font-weight-notation: named-where-possible #TODO: Look into this more

  #Function
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
  #function-url-data-uris: never #Note: Deprecated - Use either function-url-scheme-blacklist or function-url-scheme-whitelist as of 7.12.0
  function-url-quotes:
  - always
  - except:
    - empty
  function-whitespace-after: always

  #Number
  number-leading-zero: always
  number-no-trailing-zeros: true

  #String
  string-quotes: double

  #Length
  length-zero-no-unit: true

  #Unit
  unit-case: lower

  #Value
  value-keyword-case: lower

  #Value list
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: always-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0

  #Property
  property-case: lower

  #Declaration
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-space-after: always-single-line #Currently the impact isn't huge but should be a todo in the future
  declaration-colon-space-before: never
  declaration-empty-line-before:
  - never
  - ignore:
    - after-comment
    - after-declaration

  #Declaration Block
  declaration-block-semicolon-newline-after: always-multi-line #TODO: Review again
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always

  #Block
  block-closing-brace-empty-line-before: never #False Positives in nested rules - look into following feature request https://github.com/stylelint/stylelint/issues/2090
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-before: always-single-line
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always-single-line

  #TODO: Selector
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-type-case: lower

  #Selector List
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line

  #Rule
  rule-empty-line-before:
  - always-multi-line
  - ignore:
    - after-comment
    - inside-block

  #TODO: Complete Media Feature
  media-feature-name-case: lower

  #Media query list
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never-single-line

  #At-rule
  #at-rule-empty-line-before: always # TODO: Review
  at-rule-name-case: lower
  #at-rule-name-newline-after: always # TODO: Review
  at-rule-name-space-after: always
  at-rule-no-unknown: true
  at-rule-semicolon-newline-after: always

  # General
  max-empty-lines:
  - 2
  - ignore:
    - comments

  max-line-length:
  - 110
  - ignore:
     - comments

  no-eol-whitespace: true  #TODO: Review again
  no-missing-end-of-source-newline: true




#TODO: Complete this list

  #Custom Properties
  #custom-property-no-outside-root: true #TODO: Deprecated as of 7.8.0 - a stylelint plugin may exist in it's place

  #root-no-standard-properties: true #Deprecated as of 7.8.0 - a stylelint plugin may exist in it's place

  #no-browser-hacks: true #Deprecated as of 7.8.0 - a stylelint plugin may exist in it's place - See: stylelint-no-browser-hacks: https://stylelint.io/user-guide/plugins/

  #no-indistinguishable-colors: true, # Either Settings needs to be excluded or need to look into when this issue is taken care of: https://github.com/SlexAxton/css-colorguard/issues/49 - or attempt to disable around rules due to this issue - Deprecated

  #TODO: Setup supported browser list for not only this rule but theme building - https://stylelint.io/user-guide/rules/no-unsupported-browser-features/
  #no-unsupported-browser-features: true