extends: "stylelint-config-recommended"

plugins: ["stylelint-a11y",
         "stylelint-csstree-validator",
         "stylelint-declaration-block-no-ignored-properties",
         "stylelint-declaration-use-variable",]

rules:
  #From https://stylelint.io/user-guide/example-config/
  #   at-rule-blacklist: string|[]
  #   at-rule-empty-line-before: #Not really too worried about this rule
  #    - always
  #    - ignore: [after-comment]
     at-rule-name-case: lower
     at-rule-name-newline-after: always-multi-line
     at-rule-name-space-after: always
     at-rule-no-unknown: true
     at-rule-no-vendor-prefix: true
     at-rule-semicolon-newline-after: always
     at-rule-semicolon-space-before: never
  #   at-rule-whitelist: string|[]
     block-closing-brace-empty-line-before: never #False Positives sometimes in nested rules, See: https://github.com/stylelint/stylelint/issues/2090
     block-closing-brace-newline-after: always
     block-closing-brace-newline-before: always-multi-line
  #   block-closing-brace-space-after: "always" |"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line" #Not really too worried about this rule
     block-closing-brace-space-before: always-single-line
     block-no-empty: null #build process removes empty blocks, so it doesn't matter if it's in the css.
     block-opening-brace-newline-after: always-multi-line
     block-opening-brace-newline-before: always-single-line
     block-opening-brace-space-after: always-single-line
     block-opening-brace-space-before: always-single-line
     color-hex-case: lower
     color-hex-length: short
     color-no-invalid-hex: true
     color-named: never
  #   color-no-hex: true #Nope
  #   comment-empty-line-before: "always"|"never" #Not really too worried about this rule
     comment-no-empty: true
     comment-whitespace-inside: always
  #   comment-word-blacklist: string|[]
  #   custom-media-pattern: string
     custom-property-empty-line-before: always
  #   custom-property-pattern: string
     declaration-bang-space-after: never
     declaration-bang-space-before: always
     declaration-block-no-duplicate-properties:
     - true
     - ignore:
          - consecutive-duplicates-with-different-values
     declaration-block-no-shorthand-property-overrides: true
  #   declaration-block-no-redundant-longhand-properties: true #Nope
     declaration-block-semicolon-newline-after: always-multi-line
     declaration-block-semicolon-newline-before: never-multi-line
     declaration-block-semicolon-space-after: always-single-line
     declaration-block-semicolon-space-before: never
     declaration-block-single-line-max-declarations: 1 #this allows for reduced chance of merge conflicts and would be more 'truthful' when viewing a diff - see cssguidlin.es
     declaration-block-trailing-semicolon: always
     declaration-colon-newline-after: always-multi-line
     declaration-colon-space-after: always-single-line
     declaration-colon-space-before: never
     declaration-empty-line-before:
      - never
      - ignore: [after-comment, after-declaration]
     declaration-no-important: true  #NOTE: Note that !important is acceptable in utilities/overrides and should be disabled in those stylesheets where used.
  #   declaration-property-unit-blacklist: {}
  #   declaration-property-unit-whitelist: {}
  #   declaration-property-value-blacklist: {}
  #   declaration-property-value-whitelist: {}
     font-family-name-quotes: always-where-recommended
     font-family-no-duplicate-names: true
     font-family-no-missing-generic-family-keyword: true
     font-weight-notation: named-where-possible
  #   function-blacklist: string|[]
     function-calc-no-invalid: true
     function-calc-no-unspaced-operator: true
     function-comma-newline-after: always-multi-line
     function-comma-newline-before: never-multi-line
     function-comma-space-after: always-single-line
     function-comma-space-before: never
     function-linear-gradient-no-nonstandard-direction: true
     function-max-empty-lines: 0
     function-name-case: lower
     function-parentheses-newline-inside: always-multi-line
     function-parentheses-space-inside: never-single-line
     function-url-no-scheme-relative: true
     function-url-quotes:
     - always
     - except:
          - empty
  #   function-url-scheme-blacklist: string|[]
  #   function-url-scheme-whitelist: string|[]
  #   function-whitelist: string|[]
     function-whitespace-after: always
     indentation: 4
     keyframe-declaration-no-important: true
  #   keyframes-name-pattern: string
     length-zero-no-unit: true
     linebreaks: windows
     max-empty-lines:
       - 2
       - ignore:
         - comments
     max-line-length:
       - 120
       - ignore:
          - comments
  #   max-nesting-depth: int
     media-feature-colon-space-after: always
     media-feature-colon-space-before: never
  #   media-feature-name-blacklist: string|[]
     media-feature-name-case: lower
     media-feature-name-no-unknown: true
     media-feature-name-no-vendor-prefix: true
  #   media-feature-name-value-whitelist: {}
  #   media-feature-name-whitelist: string|[]
     media-feature-parentheses-space-inside: never
     media-feature-range-operator-space-after: always
     media-feature-range-operator-space-before: always
     media-query-list-comma-newline-after: always-multi-line
     media-query-list-comma-newline-before: never-multi-line
     media-query-list-comma-space-after: always-single-line
     media-query-list-comma-space-before: never-single-line
     no-descending-specificity: true
     no-duplicate-at-import-rules: true
     no-duplicate-selectors: true
     no-empty-first-line: true
     no-empty-source: true
     no-extra-semicolons: true
     no-eol-whitespace: true
     no-invalid-double-slash-comments: true
     no-missing-end-of-source-newline: true
     no-unknown-animations: true
     number-leading-zero: always
  #   number-max-precision: int #Let the browser handle max precision instead of setting a value here.
     number-no-trailing-zeros: true
  #   property-blacklist: string|[]
     property-case: lower
     property-no-unknown: true
     property-no-vendor-prefix: true
  #   property-whitelist: string|[]
     rule-empty-line-before:
       - always-multi-line
       - ignore: [ after-comment, inside-block ]
     selector-attribute-brackets-space-inside: never
  #   selector-attribute-operator-blacklist: string|[]
     selector-attribute-operator-space-after: never
     selector-attribute-operator-space-before: never
  #   selector-attribute-operator-whitelist: string|[]
     selector-attribute-quotes: always
  #   selector-class-pattern: string
  #   selector-combinator-blacklist: string|[]
     selector-combinator-space-after: always
     selector-combinator-space-before: always
  #   selector-combinator-whitelist: string|[]
     selector-descendant-combinator-no-non-space: true
  #   selector-id-pattern: string
     selector-list-comma-newline-after: always
     selector-list-comma-newline-before: never-multi-line
     selector-list-comma-space-after: always-single-line
     selector-list-comma-space-before: never
     selector-max-attribute: 1
  #   selector-max-class: int
     selector-max-combinators: 2
     selector-max-compound-selectors: 3
     selector-max-empty-lines: 0
     selector-max-id: 0
     selector-max-pseudo-class: 2
  #   selector-max-specificity:  0,2,1 #Set to what works for you - https://stylelint.io/user-guide/rules/selector-max-specificity/
     selector-max-type: 2
     selector-max-universal: 0
  #   selector-nested-pattern: string
     selector-no-qualifying-type:
      - true
      - ignore: attribute
     selector-no-vendor-prefix: true
  #   selector-pseudo-class-blacklist: string|[]
     selector-pseudo-class-case: lower
     selector-pseudo-class-parentheses-space-inside: never
     selector-pseudo-class-no-unknown: true
  #   selector-pseudo-class-whitelist: string|[]
  #   selector-pseudo-element-blacklist: string|[]
     selector-pseudo-element-case: lower
     selector-pseudo-element-colon-notation: double #"Authors must always use the double-colon syntax for these pseudo-elements" - https://bitsofco.de/pseudo-classes-pseudo-elements-and-colon-notation/
     selector-pseudo-element-no-unknown: true
  #   selector-pseudo-element-whitelist: string|[]
     selector-type-case: lower
     selector-type-no-unknown: true
     shorthand-property-no-redundant-values: true
     string-no-newline: true
     string-quotes: double
     time-min-milliseconds: 100 #According to the notes to the original issue (https://github.com/stylelint/stylelint/issues/597#issuecomment-180872504) the human eye can't see transition times under 100ms.
  #   unit-blacklist: string|[]
     unit-case: lower
     unit-no-unknown: true
  #   unit-whitelist: string|[]
     value-keyword-case: lower
     value-list-comma-newline-after: always-multi-line
     value-list-comma-newline-before: always-multi-line
     value-list-comma-space-after: always
     value-list-comma-space-before: never
     value-list-max-empty-lines: 0
     value-no-vendor-prefix: true

   #Plugin rules - https://stylelint.io/user-guide/plugins/

      # https://github.com/YozhikM/stylelint-a11y
     a11y/content-property-no-static-value: true
     a11y/font-size-is-readable: true
     #a11y/line-height-is-vertical-rhythmed: true #Disabled, Too late to do since how the site was built & designed
     a11y/media-prefers-reduced-motion: true # See https://webkit.org/blog/7551/responsive-design-for-motion/ for examples
     a11y/no-obsolete-attribute: true
     a11y/no-obsolete-element: true
     a11y/no-spread-text: true
     a11y/no-outline-none: true
     a11y/no-text-align-justify: true
     a11y/selector-pseudo-class-focus: true

   # NOTE: csstree/validator only checks if declaration values match w3c specs and browser extensions.
   # https://github.com/csstree/validator
   # The `property-no-vendor-prefix` rule will handle '-ms-grid-columns'
     csstree/validator: {ignore: ['-ms-grid-columns']}

   # https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties
     plugin/declaration-block-no-ignored-properties: true

   # https://github.com/sh-waqar/stylelint-declaration-use-variable
     sh-waqar/declaration-use-variable:
       [["color",
        { ignoreValues:
           ["currentColor"]
        }
       ]]